services:
  bds:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft_container
    environment:
      EULA: "TRUE"
      SERVER_NAME: minecraft
      LEVEL_NAME: 2023-08
      AMEMODE: survival
      DIFFICULTY: easy
  ports:
    - 19132:19132/udp
  volumes:
    - /dbs:/data
  stdin_open: true
  tty: true
volumes:
  dbs:
#volumeの場所
#/var/lib/docker/volumes/bedrock_dbs/_data/